FROM ubuntu:latest

ENV TZ Asia/Tokyo
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
  && apt-get -y install curl tzdata \
  && ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && dpkg-reconfigure --frontend noninteractive tzdata \
  && curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh \
  && .tiup/bin/tiup install playground tiflash prometheus

EXPOSE 2379
EXPOSE 3000
EXPOSE 4000
EXPOSE 9090
EXPOSE 10080
