FROM ubuntu:latest

ENV TZ Asia/Tokyo

RUN apt-get update \
  && apt-get -y install curl tzdata \
  && ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && dpkg-reconfigure --frontend noninteractive tzdata \
  && curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh \
  && source /root/.profile
  && tiup install playground
